# Generated by Django 2.1.7 on 2019-03-25 14:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mda', '0001_initial'),
        ('lga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('unreviewed', 'unreviewed'), ('approved', 'approved'), ('disapproved', 'disapproved')], default='unreviewed', max_length=15)),
                ('progress', models.CharField(blank=True, choices=[('0', '0%'), ('10', '10%'), ('20', '20%'), ('50', '50%'), ('75', '75%'), ('100', '100%')], default=0, max_length=2)),
                ('submitted_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lga.Lga')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mda.Ministry')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'All Projects',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Approved',
            fields=[
            ],
            options={
                'verbose_name': 'Approved Project',
                'verbose_name_plural': 'Approved',
                'proxy': True,
                'indexes': [],
            },
            bases=('project.project',),
        ),
        migrations.CreateModel(
            name='Disapproved',
            fields=[
            ],
            options={
                'verbose_name': 'Disapproved Project',
                'verbose_name_plural': 'Disapproved',
                'proxy': True,
                'indexes': [],
            },
            bases=('project.project',),
        ),
        migrations.CreateModel(
            name='Unreviewed',
            fields=[
            ],
            options={
                'verbose_name': 'Unreviewed Project',
                'verbose_name_plural': 'Unreviewed',
                'proxy': True,
                'indexes': [],
            },
            bases=('project.project',),
        ),
    ]
