# Generated by Django 2.1.7 on 2019-03-26 13:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lga', '0001_initial'),
        ('mda', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('picture', models.ImageField(blank=True, upload_to='media/comments/%y/%m/%d', verbose_name='image')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('submitted_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('status', models.CharField(choices=[('unreviewed', 'unreviewed'), ('approved', 'approved'), ('disapproved', 'disapproved')], default='unreviewed', max_length=15)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='project.Project')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': '.Comments',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('project', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, upload_to='media/reports/%y/%m/%d', verbose_name='image')),
                ('submitted_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('status', models.CharField(choices=[('unreviewed', 'unreviewed'), ('approved', 'approved'), ('disapproved', 'disapproved')], default='unreviewed', max_length=15)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('lga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lga.Lga')),
                ('ministry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mda.Ministry')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ApprovedComment',
            fields=[
            ],
            options={
                'verbose_name': 'Approved Comment',
                'verbose_name_plural': '.Approved Comments',
                'proxy': True,
                'indexes': [],
            },
            bases=('project.comment',),
        ),
        migrations.CreateModel(
            name='ApprovedReport',
            fields=[
            ],
            options={
                'verbose_name': 'Approved Report',
                'verbose_name_plural': 'Approved Reports',
                'proxy': True,
                'indexes': [],
            },
            bases=('project.report',),
        ),
        migrations.CreateModel(
            name='DisapprovedComment',
            fields=[
            ],
            options={
                'verbose_name': 'Disapproved Comment',
                'verbose_name_plural': '.Disapproved Comments',
                'proxy': True,
                'indexes': [],
            },
            bases=('project.comment',),
        ),
        migrations.CreateModel(
            name='DisapprovedReport',
            fields=[
            ],
            options={
                'verbose_name': 'Disapproved Report',
                'verbose_name_plural': 'Disapproved Reports',
                'proxy': True,
                'indexes': [],
            },
            bases=('project.report',),
        ),
        migrations.CreateModel(
            name='UnreviewedComment',
            fields=[
            ],
            options={
                'verbose_name': 'Unreviewed Comment',
                'verbose_name_plural': '.Unreviewed Comments',
                'proxy': True,
                'indexes': [],
            },
            bases=('project.comment',),
        ),
        migrations.CreateModel(
            name='UnreviewedReport',
            fields=[
            ],
            options={
                'verbose_name': 'Unreviewed Report',
                'verbose_name_plural': 'Unreviewed Reports',
                'proxy': True,
                'indexes': [],
            },
            bases=('project.report',),
        ),
    ]
