# Generated by Django 2.1.7 on 2019-04-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_approvedcomment_approvedreport_comment_disapprovedcomment_disapprovedreport_report_unreviewedcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default=0, max_length=4)),
                ('description', models.TextField()),
            ],
        ),
    ]
