# Generated by Django 2.1.7 on 2019-04-03 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Year'),
        ),
    ]
