# Generated by Django 2.1.7 on 2019-04-03 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20190403_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='closing',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='year',
            name='opening',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project.Year'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='lga.Lga'),
        ),
    ]
