# Generated by Django 2.1.7 on 2019-04-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20190403_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='closing',
            new_name='date_closed',
        ),
        migrations.RenameField(
            model_name='year',
            old_name='opening',
            new_name='date_open',
        ),
    ]
