# Generated by Django 2.2.6 on 2019-10-29 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20190403_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Approved',
        ),
        migrations.DeleteModel(
            name='Disapproved',
        ),
        migrations.DeleteModel(
            name='Unreviewed',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': '.Comments'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'All Projects'},
        ),
        migrations.AlterField(
            model_name='project',
            name='ministry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='mda.Ministry'),
        ),
    ]
