# Generated by Django 2.2.6 on 2019-10-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20191029_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.CharField(default=0, help_text='% Progess in percentage', max_length=3),
        ),
    ]
