# Generated by Django 2.2.6 on 2019-10-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20191030_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.CharField(blank=True, default=0, max_length=3, null=True, verbose_name='progress(%)'),
        ),
    ]
