# Generated by Django 2.2.6 on 2019-10-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20191030_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='progress_comment',
            field=models.TextField(blank=True, default='none', null=True),
        ),
    ]
