# Generated by Django 2.2.6 on 2019-10-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20191030_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='progress_comment',
            field=models.TextField(blank=True, default='none'),
        ),
    ]
