# Generated by Django 2.2.6 on 2019-10-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_auto_20191031_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='audio',
            field=models.FileField(blank=True, upload_to='media/audios/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.FileField(blank=True, upload_to='media/videos/%y/%m/%d'),
        ),
    ]
