# Generated by Django 2.2.6 on 2019-10-31 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20191031_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='video',
        ),
    ]
