# Generated by Django 2.2.7 on 2019-11-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_auto_20191107_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='submitted_by',
            new_name='submittedBy',
        ),
    ]
