# Generated by Django 2.2.7 on 2019-11-07 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0022_auto_20191107_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='submitted_by',
            new_name='submittedBy',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='report',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='report',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='report',
            name='submittedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
